---
abstract: 'A POE Component providing TCP server services for test cases'
author:
  - 'Chris Williams <chris@bingosnet.co.uk>'
build_requires:
  ExtUtils::MakeMaker: 6.42
  Test::More: 0.47
  Text::ParseWords: 0
configure_requires:
  ExtUtils::MakeMaker: 6.42
distribution_type: module
generated_by: 'Module::Install version 0.91'
license: perl
meta-spec:
  url: http://module-build.sourceforge.net/META-spec-v1.4.html
  version: 1.4
name: Test-POE-Server-TCP
no_index:
  directory:
    - examples
    - inc
    - t
provides:
  Test::POE::Server::TCP:
    file: lib/Test/POE/Server/TCP.pm
    version: 1.08
requires:
  POE: 1.004
  POE::Filter: 0
  POE::Filter::Line: 0
  POE::Wheel::ReadWrite: 0
  POE::Wheel::SocketFactory: 0
  perl: 5.6.0
resources:
  homepage: http://github.com/bingos/test-poe-server-tcp/tree
  license: http://dev.perl.org/licenses/
  repository: git://github.com/bingos/test-poe-server-tcp.git
version: 1.08
