---
abstract: 'A POE Component providing TCP server services for test cases'
author:
  - 'Chris Williams <chris@bingosnet.co.uk>'
build_requires:
  Test::More: 0.47
  Text::ParseWords: 0
configure_requires:
  ExtUtils::MakeMaker: 6.30
dynamic_config: 0
generated_by: 'Dist::Zilla version 4.200008, CPAN::Meta::Converter version 2.110930'
license: perl
meta-spec:
  url: http://module-build.sourceforge.net/META-spec-v1.4.html
  version: 1.4
name: Test-POE-Server-TCP
requires:
  POE: 1.004
  POE::Filter: 0
  POE::Filter::Line: 0
  POE::Wheel::ReadWrite: 0
  POE::Wheel::SocketFactory: 0
  perl: v5.6.0
resources:
  homepage: http://github.com/bingos/test-poe-server-tcp
  repository: http://github.com/bingos/test-poe-server-tcp
version: 1.16
